// Sample properties for agent to add
export const sampleProperties = [
  {
    id: 'agent-prop-1',
    firstName: 'John',
    lastName: 'Smith',
    contactNumber: '9876543210',
    alternateContactNumber: '8765432109',
    locality: 'Downtown',
    address: '123 Main Street, Downtown, City',
    spaceType: 'Flat',
    petsAllowed: 'Yes',
    preference: 'Any',
    bachelors: 'Male',
    type: 'Fully Furnished',
    bhk: '2',
    floor: '3',
    nearestLandmark: 'Central Park',
    washroomType: 'Western',
    coolingFacility: 'AC',
    carParking: 'Yes',
    rent: '25000',
    maintenance: '2000',
    squareFeet: '1200',
    appliances: ['Refrigerator', 'Washing Machine', 'TV'],
    amenities: ['Swimming Pool', 'Gym', 'Security'],
    about: 'Luxurious 2BHK apartment in the heart of the city with modern amenities and great connectivity.',
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXBhcnRtZW50fGVufDB8fDB8fHww&w=1000&q=80']
  },
  {
    id: 'agent-prop-2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    contactNumber: '9876543211',
    alternateContactNumber: '',
    locality: 'Suburban Heights',
    address: '456 Oak Avenue, Suburban Heights, City',
    spaceType: 'House',
    petsAllowed: 'Yes',
    preference: 'Family',
    bachelors: '',
    type: 'Semi Furnished',
    bhk: '3',
    floor: '0',
    nearestLandmark: 'City Mall',
    washroomType: 'Western',
    coolingFacility: 'AC',
    carParking: 'Yes',
    rent: '35000',
    maintenance: '3000',
    squareFeet: '1800',
    appliances: ['Refrigerator', 'Microwave'],
    amenities: ['Park', 'Security', 'Power Backup'],
    about: 'Beautiful 3BHK independent house with garden space, perfect for families looking for a peaceful neighborhood.',
    photos: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG91c2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80']
  },
  {
    id: 'agent-prop-3',
    firstName: 'Michael',
    lastName: 'Brown',
    contactNumber: '9876543212',
    alternateContactNumber: '8765432101',
    locality: 'Tech Park',
    address: '789 Innovation Street, Tech Park, City',
    spaceType: 'Office',
    petsAllowed: 'No',
    preference: 'Any',
    bachelors: '',
    type: 'Fully Furnished',
    bhk: '1',
    floor: '5',
    nearestLandmark: 'Tech Hub',
    washroomType: 'Western',
    coolingFacility: 'AC',
    carParking: 'Yes',
    rent: '45000',
    maintenance: '5000',
    squareFeet: '1000',
    appliances: ['Refrigerator', 'Microwave', 'Water Purifier'],
    amenities: ['Security', 'Power Backup', 'Lift', 'Parking'],
    about: 'Modern office space in the tech district, ideal for startups and small businesses. 24/7 access with all amenities.',
    photos: ['https://images.unsplash.com/photo-1497366754035-f200968a6e72?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8b2ZmaWNlJTIwc3BhY2V8ZW58MHx8MHx8fDA%3D&w=1000&q=80']
  },
  {
    id: 'agent-prop-4',
    firstName: 'Emily',
    lastName: 'Davis',
    contactNumber: '9876543213',
    alternateContactNumber: '',
    locality: 'College Town',
    address: '101 Student Lane, College Town, City',
    spaceType: 'PG',
    petsAllowed: 'No',
    preference: 'Bachelors',
    bachelors: 'Female',
    type: 'Semi Furnished',
    bhk: '1',
    floor: '2',
    nearestLandmark: 'University Campus',
    washroomType: 'Indian',
    coolingFacility: 'Fan',
    carParking: 'No',
    rent: '8000',
    maintenance: '1000',
    squareFeet: '500',
    appliances: ['Refrigerator', 'Water Purifier', 'Geyser'],
    amenities: ['Security', 'Power Backup'],
    about: 'Affordable PG accommodation for female students near the university campus. Meals included in the rent.',
    photos: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGhvc3RlbHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80']
  },
  {
    id: 'agent-prop-5',
    firstName: 'Robert',
    lastName: 'Wilson',
    contactNumber: '9876543214',
    alternateContactNumber: '8765432102',
    locality: 'Market Square',
    address: '234 Commerce Road, Market Square, City',
    spaceType: 'Shop',
    petsAllowed: 'No',
    preference: 'Any',
    bachelors: '',
    type: 'Non Furnished',
    bhk: '1',
    floor: '0',
    nearestLandmark: 'Central Market',
    washroomType: 'Western',
    coolingFacility: 'AC',
    carParking: 'Yes',
    rent: '50000',
    maintenance: '3000',
    squareFeet: '800',
    appliances: [],
    amenities: ['Security', 'Power Backup', 'Parking'],
    about: 'Prime commercial shop space in the busiest market area with high footfall. Perfect for retail businesses.',
    photos: ['https://images.unsplash.com/photo-1582640731057-9a3c3756d5d1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2hvcCUyMHNwYWNlfGVufDB8fDB8fHww&w=1000&q=80']
  }
];